# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_RShift <- function(a, b) {
    .Call(`_HVcpp_cpp_RShift`, a, b)
}

cpp_LShift <- function(a, b) {
    .Call(`_HVcpp_cpp_LShift`, a, b)
}

computeGCD <- function(a, b) {
    .Call(`_HVcpp_computeGCD`, a, b)
}

computeLCM <- function(a, b) {
    .Call(`_HVcpp_computeLCM`, a, b)
}

cpp_gcd_lcm <- function(x, y) {
    .Call(`_HVcpp_cpp_gcd_lcm`, x, y)
}

cpp_gcd <- function(x, y) {
    .Call(`_HVcpp_cpp_gcd`, x, y)
}

cpp_lcm <- function(x, y) {
    .Call(`_HVcpp_cpp_lcm`, x, y)
}

armaMatMult <- function(A, B) {
    .Call(`_HVcpp_armaMatMult`, A, B)
}

eigenMatTrans <- function(A) {
    .Call(`_HVcpp_eigenMatTrans`, A)
}

eigenMatMult <- function(A, B) {
    .Call(`_HVcpp_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_HVcpp_eigenMapMatMult`, A, B)
}

cpp_md5 <- function(str, times = 1L) {
    .Call(`_HVcpp_cpp_md5`, str, times)
}

cpp_primes <- function(n, first = FALSE) {
    .Call(`_HVcpp_cpp_primes`, n, first)
}

rcpp_hello_world <- function() {
    .Call(`_HVcpp_rcpp_hello_world`)
}

cpp_rtrim <- function(s, t = " \t\n\r\f\v") {
    .Call(`_HVcpp_cpp_rtrim`, s, t)
}

cpp_ltrim <- function(s, t = " \t\n\r\f\v") {
    .Call(`_HVcpp_cpp_ltrim`, s, t)
}

cpp_trim <- function(s, t = " \t\n\r\f\v") {
    .Call(`_HVcpp_cpp_trim`, s, t)
}

cpp_tolower <- function(s) {
    .Call(`_HVcpp_cpp_tolower`, s)
}

cpp_toupper <- function(s) {
    .Call(`_HVcpp_cpp_toupper`, s)
}

cpp_strlen <- function(s) {
    .Call(`_HVcpp_cpp_strlen`, s)
}

cpp_charAt <- function(s, w) {
    .Call(`_HVcpp_cpp_charAt`, s, w)
}

cpp_explode <- function(s, sep = "") {
    .Call(`_HVcpp_cpp_explode`, s, sep)
}

cpp_implode <- function(r, sep = "") {
    .Call(`_HVcpp_cpp_implode`, r, sep)
}

cpp_str_replace <- function(search, replace, subject) {
    .Call(`_HVcpp_cpp_str_replace`, search, replace, subject)
}

cpp_str_repeat <- function(s, times) {
    .Call(`_HVcpp_cpp_str_repeat`, s, times)
}

